### ISSUE TITLE
Definir estrutura da tabela `WishList`

### ISSUE THREAD

**Issue by felipemotarocha** [felipemotarocha/fullstackweek-store#20]
- Tabela deve armazenar as listas de desejos dos usuários.
- Um usuário pode ter várias listas de desejos.
- Uma lista de desejos pode ter vários produtos

**Comment by rafaelluiis2315** [comment]
Fazendo 🏗️

**Comment by rafaelluiis2315** [comment]
Feito no [PR](https://github.com/felipemotarocha/fullstackweek-store/issues/21) de @JoaoFPedro ✅
