### ISSUE TITLE
Garantir que um produto possa ser adicionado a uma lista de desejos

### ISSUE THREAD

**Issue by felipemotarocha** [felipemotarocha/fullstackweek-store#25]
- Quando o usuário visualizar um produto, ele deve ter a opção de adicioná-lo a uma lista de desejo.
- Ao clicar no botão "Adicionar a lista de desejo", abrir um [`Dialog`](https://ui.shadcn.com/docs/components/dialog) com as listas do usuário.
- Ao clicar em uma lista, adicionar o produto à ela
- Exibir uma mensagem de sucesso ao adicionar
- Um produto não pode ser adicionado a mesma lista mais de uma vez

**Comment by RafaelMatos** [comment]
Fazendo 🏗️
