### ISSUE TITLE
Adicionar botão de favorito ao produto e inserir na tabela Wishlist

### ISSUE THREAD

**Issue by jrneliodias** [felipemotarocha/fullstackweek-store#36]
Objetivo:
-  Criar botão "⭐ Favorito" no componente produto.
- Adicionar produto a tabela "Wishlist" 

![image](https://github.com/felipemotarocha/fullstackweek-store/assets/69831915/3eeaeedf-14b9-4d6d-bbaf-6b8fd61cce5b)

**Comment by rafaelluiis2315** [comment]
Fazendo 🏗️
