### ISSUE TITLE
Status do pedido não está sendo atualizado para PAYMENT_CONFIRMED

### ISSUE THREAD

**Issue by aledosreis** [felipemotarocha/fullstackweek-store#9]
Os pedidos não estão atualizando para PAYMENT_CONFIRMED

![image](https://github.com/felipemotarocha/fullstackweek-store/assets/59235732/b706bcf8-499e-4ead-87eb-9b1d94bda986)

**Comment by aledosreis** [comment]
Verificado que o problema é referente as configurações do Stripe.
1. No dashboard do stripe havia sido configurado o endpoint de produção como sendo a página home. Foi alterado para ser a rota de API (Não me recordo se nas lives foi configurado corretamente)
2. Nas variaveis de ambiente da aplicação em produção foi salvo na variavel STRIPE_WEBHOOK_SECRET_KEY o valor referente ao ID do webhook dentro do stripe, devendo ser corrigido para a secret key. (Exemplo na imagem abaixo, o valor em vermelho foi configurado quando deveria ser o valor secreto em amarelo)
![image](https://github.com/felipemotarocha/fullstackweek-store/assets/59235732/1ed7f7e6-9942-4473-87b0-b6e1809f4c39)

Após a correção dos dois valores a atualização dos novos pedidos para o status de PAYMENT_CONFIRMED ocorre como esperado.

@felipemotarocha Por se tratar de um problema relacionado a variáveis de ambiente, ocorrendo atualmente apenas em ambiente de produção, essa correção não é aplicável via PR.

**Comment by felipemotarocha** [comment]
Boa, obrigado pelo aviso, meu mano! Vou deixar o issue aberto só pra tê-lo como referência. Podemos atualizar o README com essa informação também.

**Comment by aledosreis** [comment]
Boa ideia, atualizar o README. Não vou estar no PC no fim de semana, mas semana que vem vou tentar fazer a alteração com instruções de execução em ambiente dev e deploy também. Assim podemos também fechar a issue, e deixamos documentado.

**Comment by felipemotarocha** [comment]
Sensacional, Alessandro! Obrigado, meu irmão! 🚀
